### ISSUE TITLE
Image uploader extension: Only single upload currently allowed

### ISSUE THREAD

**Issue by MichaelHeydon** [michaelsharman/LT#6]
Hi Michael, 

Thanks for providing these additional Learnosity extensions. I was looking into the image uploader extension and observed the issue below: 

https://github.com/michaelsharman/LT/assets/74880856/6225556f-b647-4047-9962-f436c425029e

As per the video it currently only allows a single image to be uploaded. After the first upload it currently reverts back to the original upload modal which has the 512kb restriction. Would it be possible to resolve this?

**Comment by michaelsharman** [comment]
Thanks Michael, this one is tricky. I _think_ there is a conflict with the Author API controlled close buttons and the listener for the image uploader. I added a small change, it's very hard to replicate for me. Let me know how you go.

I also fixed a similar issue when you move out of the current question edit screen and add a new question. The same issue was occurring, that should be resolved now.

Update the library, you should get 2.13.0

**Comment by michaelsharman** [comment]
Apologies, another issue was found. Latest fix is 2.13.2

**Comment by MichaelHeydon** [comment]
Thanks very much Michael, I'll test shortly and let you know how I go.

**Comment by MichaelHeydon** [comment]
Appears to be working well thanks :+1:
