### ISSUE TITLE
Image uploader extension: File browser issues within 'browse files' browser

### ISSUE THREAD

**Issue by MichaelHeydon** [michaelsharman/LT#8]
It appears the current restrictions within `Uppy` may not be working as expected? For example here's the default image browser within a folder with a few of the restricted image types:
![Screenshot from 2024-06-27 15-45-00](https://github.com/michaelsharman/LT/assets/74880856/978824ce-5f46-44d5-b570-5931e58b8c51)

And here's within using Uppy:
![Screenshot from 2024-06-27 15-29-21](https://github.com/michaelsharman/LT/assets/74880856/0aff26e3-40f8-4e09-add0-1e8fbff613a2)

Having a quick look at the Uppy documentation, it looks like everything is as expected. Are you also experiencing unusual file restrictions?

**Comment by michaelsharman** [comment]
I added restrictions in Uppy because of the limitations in file support within the Learnosity API. For instance, the API doesn't support webp or avif.

I wonder if the reason files aren't showing in the 2nd screenshot because of missing file extensions in the name?

**Comment by MichaelHeydon** [comment]
Actually I can see it may be something to do specifically within our environment. Here's the difference upon selecting _browse files_:
![Screenshot from 2024-06-28 15-56-33](https://github.com/michaelsharman/LT/assets/74880856/6be59060-05e8-49c7-895a-be5f9025c704)
![Screenshot from 2024-06-28 15-56-15](https://github.com/michaelsharman/LT/assets/74880856/5ebfcef6-17ca-458a-97f7-89b100134d36)

In which case I'm at a loss as to what could be happening...

**Comment by michaelsharman** [comment]
What is your environment? On a mac you can see all files, but unsupported files are greyed out.
<img width="565" alt="Screenshot 2024-07-01 at 9 34 43 AM" src="https://github.com/michaelsharman/LT/assets/663796/8a8cd34a-6087-406a-8e89-6b340deb67b8">

**Comment by MichaelHeydon** [comment]
Yeah I've tried Windows, Mac, and Linux, all have the same result, with no files able to be selected. I'll have to do some more extensive testing to try and isolate what's causing the issue within our environment I suspect.

**Comment by michaelsharman** [comment]
Are we ok to close this @MichaelHeydon?

**Comment by MichaelHeydon** [comment]
Hey Michael, I've done a bit more testing on this today and I wonder if it could be security related?

I've tested with the same `Uppy` setup in our environment: 
```
import Uppy from "@uppy/core";
import Dashboard from "@uppy/dashboard";
import Compressor from "@uppy/compressor";
import ImageEditor from "@uppy/image-editor";

import "@uppy/core/dist/style.min.css";
import "@uppy/dashboard/dist/style.min.css";
import "@uppy/image-editor/dist/style.min.css";

const state = {
    observer: null,
    observedElements: new Map(),
    renderedCss: false,
    options: {
        quality: 0.7,
        maxWidth: 1500,
        maxHeight: 1500,
    },
    upload: {
        request: null,
        security: null,
        // uriUploadForm: checkUploadFormUri("https://authorapi.learnosity.com/latest-lts/assets/uploadform"),
    },
    uppy: null,
};

state.uppy = new Uppy({
    debug: false,
    autoProceed: false,
    restrictions: {
        maxNumberOfFiles: 1,
        minNumberOfFiles: 1,
        allowedFileTypes: ["image/gif", "image/jpeg", "image/png", "image/svg+xml"],
    },
})
    .use(Dashboard, {
        inline: true,
        width: 790,
        height: 350,
        autoOpen: null,
        disableStatusBar: true,
        target: "#uppy-dashboard",
        showProgressDetails: false,
        proudlyDisplayPoweredByUppy: false,
    })
    .use(Compressor, {
        quality: state.options.quality,
        convertSize: 500000,
        convertTypes: ["image/png"],
        maxHeight: state.options.maxHeight,
        maxWidth: state.options.maxWidth,
    })
    .use(ImageEditor, { target: Dashboard });
```

And it works as expected:
![Screenshot from 2024-07-09 08-54-31](https://github.com/michaelsharman/LT/assets/74880856/4d30b1f3-546e-4acb-8746-b575f222f645)

Is there anything within the _Learnosity upload UI (iframe)_ that ensures files within the file upload can be selected cross domain or anything?

**Comment by michaelsharman** [comment]
> Is there anything within the Learnosity upload UI (iframe) that ensures files within the file upload can be selected cross domain or anything?

Nothing that I can see. All testing works for me on Chrome, Firefox, and Safari (including Chrome on Windows). I asked a other people to test as well (different network/machine) which was fine.

I'm at a bit of a loss. This is all pre-Learnosity upload. It's all Uppy, just browsing for files. Very strange that your separate set up works (with the same configuration).

**Comment by MichaelHeydon** [comment]
I've also pulled your repo in to test, if there's anything I can log or change that could offer any insights?

**Comment by michaelsharman** [comment]
You could set the log level to `DEBUG` [here](https://github.com/michaelsharman/LT/issues/8#issuecomment-2216704500) and enable Uppy debugging [here](https://github.com/michaelsharman/LT/blob/main/src/authoring/extensions/ui/imageUploader/index.js#L247).

**Comment by MichaelHeydon** [comment]
Thanks I'll check them on Thursday. Can you confirm the first link please? Looks like it just links to my comment.

**Comment by michaelsharman** [comment]
Sorry, [here is the line](https://github.com/michaelsharman/LT/blob/main/src/authoring/extensions/ui/imageUploader/index.js#L105).

**Comment by MichaelHeydon** [comment]
No insight unfortunately. I'll add an issue on Uppy's github as the next step.

**Comment by MichaelHeydon** [comment]
OK, I see what's going on...

Inspecting the element reveals there's a hidden `<input>` that happens to sit pretty much perfectly over our setup:
![Screenshot from 2024-07-15 18-04-11](https://github.com/user-attachments/assets/2e6bc73f-59c1-4f8b-8ffc-5f2c81ad9403)

So I was selecting that, not the browse files button. This Learnosity style is being applied:
```
.lrn input[type=file] {
    display: block;
}
```

The reason it's not being applied in your demo environment is because a bootstrap rule is most specific:
![Screenshot from 2024-07-15 18-08-41](https://github.com/user-attachments/assets/dbbf2429-f97a-4e05-8842-f1c77e2d94c1)

There may be an alternative, but adding:
```
.lrn .uppy-Dashboard-input[type=file] {
    display: none;
}
```
into the `injectCSS` resolves the issue. Are you able to update with this or an alternative solution?

**Comment by michaelsharman** [comment]
That's very strange. I have a vanilla test page (no Bootstrap), and I still couldn't replicate it.

The CSS line you quoted is coming from the underlying Questions API. I added your line to `injectCSS` and published 2.14.1. Because I can't replicate it, can you test it to see if it's working for you now?

**Comment by MichaelHeydon** [comment]
Thanks Michael. That's resolved now. :+1:

**Comment by michaelsharman** [comment]
Excellent! Thanks for your help.
